name: clang-tidy-review

on:
  pull_request:
    paths:
      - '**.h'
      - '**.hpp'
      - '**.cpp'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.3"

      - name: Run clang-tidy
        uses: ZedThree/clang-tidy-review@v0.18.0
        id: review
        with:
          build_dir: build
          apt_packages: libxml2,libxml2-dev,libtinfo-dev,zlib1g-dev,libzstd-dev,curl
          exclude: "test/*,unittests/*,benchmark/*,demos/*"
          split_workflow: true
          cmake_command: >
            set -x &&
            mkdir micromamba && cd micromamba && curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba &&
            export MAMBA_ROOT_PREFIX=/github/workspace/micromamba &&
            eval "$(./bin/micromamba shell hook -s posix)" &&
            micromamba create -n xeus-cpp -y --log-level warning -f /github/workspace/environment-dev.yml &&
            micromamba activate xeus-cpp &&
            cd .. &&
            git config --global --add safe.directory /github/workspace &&
            cmake . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=On

      - name: Upload artifacts
        uses: ZedThree/clang-tidy-review/upload@v0.18.0
