name: clang-tidy-review

on:
  pull_request:
    paths:
      - '**.h'
      - '**.hpp'
      - '**.cpp'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  review:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v7

      - name: Run clang-tidy
        uses: ZedThree/clang-tidy-review@v0.23.1
        id: review
        with:
          build_dir: build
          exclude: "test/*,unittests/*,benchmark/*,demos/*"
          split_workflow: true
          config_file: .clang-tidy
          cmake_command: >
            set -eu &&
            python3 -c "import hashlib, pathlib, urllib.request; p = pathlib.Path('micromamba'); urllib.request.urlretrieve('https://github.com/mamba-org/micromamba-releases/releases/download/2.8.1-0/micromamba-linux-64', p); assert hashlib.sha256(p.read_bytes()).hexdigest() == '9689782d863c05a1bf5d2d371ba527104e7a4eb4310c1637d8653b751aed9c82'" &&
            chmod +x ./micromamba &&
            git config --global --add safe.directory /github/workspace &&
            MAMBA_ROOT_PREFIX="$PWD/.micromamba" ./micromamba create -n xeus-cpp -y --log-level warning -f environment-dev.yml &&
            MAMBA_ROOT_PREFIX="$PWD/.micromamba" ./micromamba run -n xeus-cpp cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            
      - name: Upload artifacts
        uses: ZedThree/clang-tidy-review/upload@v0.23.1
